# Generated by Django 5.0.4 on 2024-05-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_book_status_delete_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
