# Generated by Django 5.0.4 on 2024-05-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='time1',
            field=models.CharField(default='00:00', max_length=12),
        ),
    ]
