# Generated by Django 5.0.4 on 2024-05-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_book_time1'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='controle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='time2',
            field=models.CharField(default='00:00', max_length=12),
        ),
    ]
