# Generated by Django 5.0.6 on 2024-05-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0014_book_is_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
