# Generated by Django 5.0.6 on 2024-05-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0015_book_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='urgent',
            field=models.CharField(default='', max_length=100),
        ),
    ]
