# Generated by Django 5.0.6 on 2024-05-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0016_book_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Nands',
            field=models.CharField(default='', max_length=100),
        ),
    ]
