# Generated by Django 5.0.6 on 2024-05-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0017_book_nands'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='conforme',
            field=models.CharField(default='', max_length=100),
        ),
    ]
