# Generated by Django 5.0.6 on 2024-06-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0019_book_is_confrome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_confrome',
            new_name='is_conforme',
        ),
    ]
