# Generated by Django 5.0.6 on 2024-06-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0020_rename_is_confrome_book_is_conforme'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fiche',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='implutation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
