# Generated by Django 5.0.6 on 2024-06-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0023_book_time_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time_difference',
            field=models.CharField(default='', max_length=12),
        ),
    ]
