# Generated by Django 5.0.6 on 2024-06-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0024_alter_book_time_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fiche',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='implutation',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_difference',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
